backend:
  name: git-gateway
  branch: main

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "products"
    label: "Products"
    folder: "content/products"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Price", name: "price", widget: "number", value_type: "float" }
      - {
          label: "Category",
          name: "category",
          widget: "select",
          options: ["weekly", "freezer"]
        }
      - { label: "Image", name: "image", widget: "image" }
      - label: "Macros"
        name: "macros"
        widget: "object"
        fields:
          - { label: "Protein", name: "protein", widget: "string" }
          - { label: "Carbs", name: "carbs", widget: "string" }
          - { label: "Fat", name: "fat", widget: "string" }